In [1]:
import numpy as np

In [2]:
xi = np.array([
    [3, 2, 2],
    [0, 1, 2],
    [1, 3, 2]], dtype=np.uint8)
#xp = np.unpackbits(xi).reshape((3, 3, 8))

# better version of: xp = np.stack([xi & (1 << 0), xi & (1 << 1)], axis=2)
xp = (xi[:,:,None] & (1 << np.arange(2)) > 0).astype(bool)


np.packbits(xp, bitorder='little', axis=2).squeeze(axis=2)

array([[3, 2, 2],
       [0, 1, 2],
       [1, 3, 2]], dtype=uint8)

In [3]:
(xi[:,:,None] & (1 << np.arange(2)) > 0).astype(bool)

array([[[ True,  True],
        [False,  True],
        [False,  True]],

       [[False, False],
        [ True, False],
        [False,  True]],

       [[ True, False],
        [ True,  True],
        [False,  True]]])

In [4]:
np.squeeze(np.packbits(np.array([
    [[1, 1], [0, 1], [0, 1]],
    [[0, 0], [1, 0], [0, 1]],
    [[1, 0], [1, 1], [0, 1]]
]), bitorder='little', axis=2), axis=2)

array([[3, 2, 2],
       [0, 1, 2],
       [1, 3, 2]], dtype=uint8)

In [13]:
%run codecs.py

In [14]:
codec = PackGeneticBits()

In [15]:
codec.encode(xi)

array([  6, 212, 155,  64], dtype=uint8)

In [18]:
codec.decode(codec.encode(xi)).reshape(xi.shape)

array([[3, 2, 2],
       [0, 1, 2],
       [1, 3, 2]], dtype=uint8)